apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjpeg
  labels:
    app: mjpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjpeg
  template:
    metadata:
      labels:
        app: mjpeg
    spec:
      containers:
      - name: mjpeg
        image: gcr.io/binocular-cv/mjpeg:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mjpeg
spec:
  selector:
    app: mjpeg
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
