apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjpeg
  labels:
    app: mjpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjpeg
  template:
    metadata:
      labels:
        app: mjpeg
    spec:
      containers:
      - name: mjpeg
        image: gcr.io/binocular-cv/mjpeg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /bin/sh
        - -c
        - "echo \"Starting MJPEG service...\" && mkdir -p /mnt/nfs/jobs/mjpeg && ./mjpeg 2>&1 | tee /mnt/nfs/jobs/mjpeg/${POD_NAME}.log"
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mjpeg
spec:
  selector:
    app: mjpeg
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
